### ISSUE TITLE
Some help would be appreciated

### ISSUE THREAD

**Issue by stefanbesler** [stefanbesler/struckig#2]
Hey @pantor,

I am making good  progress for trajectories with 1 dof with the port, but I have issues with some test cases.
When calculating a trajectory for

(p0=0; v0=0; a0=0) to (pf=0.1,vf=0,af=0) with (v_max=2000, a_max=20000, j_max=200000)

I don't get any solution for trajectories like this, but my expections are the either a_max or j_max have to be significantly reduced. However, ruckig doesn't seem to take care of something like this?

**Comment by pantor** [comment]
Hi @stefanbesler! Ruckig has some numerical limits for the input, but your case should (and does) work just fine. I suspect that there is some issue in the equations of the `position.cpp` file.

You can uncomment [lines 52-58](https://github.com/pantor/ruckig/blob/07f9e68efda73c5dbfce29f502e0e71dd0ade805/include/ruckig/block.hpp#L52) of `block.hpp` to print the found profiles. In your case, Ruckig finds a `UP_NONE_UDDU` profile, which is calculated in [line 228](https://github.com/pantor/ruckig/blob/07f9e68efda73c5dbfce29f502e0e71dd0ade805/src/position-step1.cpp#L228) of `position.hpp`. The final numerical calculation is done in line [231](https://github.com/pantor/ruckig/blob/07f9e68efda73c5dbfce29f502e0e71dd0ade805/src/position-step1.cpp#L231). 

So maybe you can have a look at your corresponding ported code. Maybe there is something wrong with your `cbrt` function?

**Comment by stefanbesler** [comment]
Ok, if you say there should be a valid profile for this case, this already helps a lot

**Comment by stefanbesler** [comment]
@pantor good catch, the precision of my cbrt just wasn't good enough - I used 1E-4 as condition to break from the loop, thanks.
Regarding the numeric limits. One solution might be to calculate a PositionStep2 profile if no PositionStep1 profile can be found and use stime = acc_max / j_max as tf ?
